#group function
group_fun1=function(image0,folds=6,drop_margin=FALSE){
  ymin=2; ymax=383
  xmin=65;xmax=369
  group_image0=data.frame()
  x0=xmin
  while(x0<=xmax){
    y0=ymin
    while(y0<=ymax){
      fold_num=sample(1:folds,1)
      temp_image0=image0%>%
        filter(y>=y0&y<=(y0+7)
               &x>=x0&x<=(x0+7)
               &label!=0)
      if(drop_margin&fold_num!=folds){
        numrow=image0%>%
          filter(y>=y0&y<=(y0+7)
                 &x>=x0&x<=(x0+7))%>%
          nrow()
        label_sum=temp_image0%>%
          dplyr::select(label)%>%
          sum()%>%
          abs()
        if(label_sum!=numrow){
          temp_image0=data.frame()
        }
      }
      if(nrow(temp_image0)!=0){
        temp_image0=temp_image0%>%
          mutate(fold=fold_num)
        group_image0=rbind(group_image0,temp_image0)
      }
      y0=y0+8
    }
    x0=x0+8
    #print(x)
  }
  return(group_image0)
}
# group pixels in blocks and assign group number, not done yet.
group_fun=function(img,size){
  ymin=min(img$y);ymax=max(img$y)
  xmin=min(img$x);xmax=max(img$x)
  group_image=data.frame()
  x=xmin
  while(x<=xmax){
    y=ymin
    while(y0<=ymax){
      fold_num=sample(1:folds,1)
      temp_image0=image0%>%
        filter(y>=y0&y<=(y0+7)
               &x>=x0&x<=(x0+7)
               &label!=0)
      if(drop_margin&fold_num!=folds){
        numrow=image0%>%
          filter(y>=y0&y<=(y0+7)
                 &x>=x0&x<=(x0+7))%>%
          nrow()
        label_sum=temp_image0%>%
          dplyr::select(label)%>%
          sum()%>%
          abs()
        if(label_sum!=numrow){
          temp_image0=data.frame()
        }
      }
      if(nrow(temp_image0)!=0){
        temp_image0=temp_image0%>%
          mutate(fold=fold_num)
        group_image0=rbind(group_image0,temp_image0)
      }
      y0=y0+8
    }
    x0=x0+8
    #print(x)
  }
  return(0)
}


CVmaster=function(generic_fun="logistics",X,y,K,loss_fun="accuracy",drop_margin0=FALSE){
  train_model="factor(label)~NDAI+CORR+SD"
  CV_data=cbind(X,y)
  group_data=group_fun1(CV_data,drop_margin = drop_margin0)
  valid_acc=c()
  for(i in 1:(K-1)){
    train_data=group_data%>%filter(fold!=i&fold!=K)
    valid_data=group_data%>%filter(fold==i)
    y_valid=valid_data%>%dplyr::select(label)
    if(generic_fun=="logistics"){
      clf=glm(train_model,train_data,family = "binomial")
      valid_pred=predict(clf,valid_data,type="reponse")
      if(loss_fun=="accuracy"){
        valid_pred=sign(valid_pred-0.5)
        valid_acc=c(valid_acc,mean(valid_pred==y_valid))
      }
    }
    if(generic_fun=="QDA"){
      clf=qda(formula=as.formula(train_model),data=train_data)
      valid_pred=list(predict(clf,valid_data)$class)
      if(loss_fun=="accuracy"){
        valid_acc=c(valid_acc,mean(valid_pred==y_valid))
      }
    }
    if(generic_fun=="LDA"){
      clf=lda(formula=as.formula(train_model),data=train_data)
      valid_pred=list(predict(clf,valid_data)$class)
      if(loss_fun=="accuracy"){
        valid_acc=c(valid_acc,mean(valid_pred==y_valid))
      }
    }
  }
  train_data=group_data%>%filter(fold!=K)
  test_data=group_data%>%filter(fold==K)
  y_test=test_data%>%dplyr::select(label)
  if(generic_fun=="logistics"){
    clf=glm(train_model,train_data,family="binomial")
    prob.pred=predict(clf,test_data,type="response")
    if(loss_fun=="accuracy"){
      test_pred=sign(clf.pred-0.5)
      test_acc=mean(test_pred==y_test)
    }
  }
  if(generic_fun=="QDA"){
    clf=qda(formula=as.formula(train_model),data=train_data)
    clf.pred=predict(clf,test_data)
    test_pred=clf.pred$class
    prob.pred=clf.pred$posterior[,2]
    if(loss_fun=="accuracy"){
      test_acc=mean(test_pred==y_test)
    }
  }
  if(generic_fun=="LDA"){
    clf=lda(formula=as.formula(train_model),data=train_data)
    clf.pred=predict(clf,test_data)
    test_pred=clf.pred$class
    prob.pred=clf.pred$posterior[,2]
    if(loss_fun=="accuracy"){
      test_acc=mean(test_pred==y_test)
    }
  }
  return(list(acc=c(valid_acc,mean(valid_acc),test_acc),
              prob=prob.pred,
              gold=y_test))
}
