---
title: "proj2_plots"
author: "Shiqi Liu"
date: "11/29/2022"
output: pdf_document
---
data and packages
```{r}
require(tidyverse)
require(rstanarm)
require(magrittr)
require(rstan)
require(plyr)
require(patchwork)
require(scales)
require(psych)
require(GGally)
require(gridExtra)
require(MASS)
require(e1071)
require(naivebayes)
require(class)
require(caTools)
require(ROCR)
require(caret)
require(rpart)
require(car)
require(FactoMineR)
require(modeest)
require(ggrepel)
require(randomForest)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(fig.align = 'center')
```

```{r read data, message=F, warning=F, echo=F}
image1=read.table("data/imagem1.txt")
colnames(image1)=c("y","x","label","NDAI","SD","CORR","DF","CF","BF","AF","AN")
image2=read.table("data/imagem2.txt")
colnames(image2)=c("y","x","label","NDAI","SD","CORR","DF","CF","BF","AF","AN")
image3=read.table("data/imagem3.txt")
colnames(image3)=c("y","x","label","NDAI","SD","CORR","DF","CF","BF","AF","AN")
```

1(b) percent-table
```{r}
png(file="plot/percent-table.png",units="in",width=4,
    height=1.2 ,pointsize=12,res=300)
rbind(image1%>%dplyr::select(3)%>%mutate(image="Image1"),
      image2%>%dplyr::select(3)%>%mutate(image="Image2"),
      image3%>%dplyr::select(3)%>%mutate(image="Image3"))%>%
  group_by(image,label)%>%
  count()%>%
  pivot_wider(names_from = label,values_from = freq)%>%
  mutate(sum1=rowSums(.[,2:4]))%>%
  mutate(`not cloud`=percent(`-1`/sum1,accuracy=0.01),
         unlabeled=percent(`0`/sum1,accuracy=0.01),
         cloud=percent(`1`/sum1,accuracy=0.01),
         Total="100%")%>%
  dplyr::select(c(1,6:9))%>%
  grid.table( rows = NULL)
dev.off()
  # knitr::kable(caption = "Percentage of Percentage of not cloud, unlabeled and cloud for each image.")%>%
  # save_kable("plot/percent-table.png")
```

1(b) labeled-images
```{r}
png(file="plot/labeled-images.png",units="in",width=7.5,
    height=3,pointsize=12,res=300)
p1=rbind(image1%>%dplyr::select(1:3)%>%mutate(image="Image1"),
      image2%>%dplyr::select(1:3)%>%mutate(image="Image2"),
      image3%>%dplyr::select(1:3)%>%mutate(image="Image3"))%>%
  ggplot(aes(x,y,color=factor(label)))+
  geom_point(shape=15,size=0.000000000001)+
  facet_wrap(~image)+
  coord_fixed()+
  guides(color = guide_legend(override.aes = list(size = 10)))+
  labs(x="x coordinate",y="y coordinate")+
  scale_color_manual(values=c("#501d8a", "#1c8041", "#e55709"),
                     labels=c("not cloud","unlabeled","cloud"))+
  theme(legend.position="right",legend.title=element_blank())
p1
dev.off()
```
1(c) pairwise-correlations
```{r}
png(file="plot/pairwise-correlations.png",units="in",width=6,
    height=4,pointsize=12,res=300)
ggally_mysmooth <- function(data, mapping, ...){
  ggplot(data = data, mapping=mapping) +
    geom_density(  fill=NA)
}
df1=rbind(image1,image2,image3)%>%
  dplyr::select(3:11)
df1%>%
  filter(label!=0)%>%
  #dplyr::select(2:9)%>%
  ggpairs(mapping = ggplot2::aes(color=factor(label)),
          columns=2:9,
          lower = list(continuous = wrap("points", alpha = 0.2, size=0.00001)),
          upper = list(continuous = wrap("cor", size = 2.2)),
          diag = list(continuous = ggally_mysmooth)
          )
dev.off()
```
1(c) label-features
```{r}
png(file="plot/label-feature1.png",units = "in",width=14,
    height=7,pointsize=12,res=300)
df2=df1%>%
  filter(label!=0)

p1=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=NDAI,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and NDAI",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$NDAI),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$NDAI),4)))

p2=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=SD,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and SD",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$SD),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$SD),4)))

p3=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=CORR,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and CORR",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$CORR),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$CORR),4)))

p4=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=DF,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and DF",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$DF),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$DF),4)))

p5=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=CF,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and CF",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$CF),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$CF),4)))

p6=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=BF,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and BF",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$BF),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$BF),4)))

p7=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=AF,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and AF",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$AF),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$AF),4)))

p8=df1%>%
  filter(label!=0)%>%
  ggplot(aes(x=label,y=AN,group=factor(label)))+
  geom_boxplot()+
  labs(title="Label and AN",
       subtitle = paste0("Correlation with unlabelled =",
                         round(cor(df1$label,df1$AN),4),
                         "\nCorrelation without unlabelled =",
                         round(cor(df2$label,df2$AN),4)))

p1+p2+p3+p4+p5+p6+p7+p8+plot_layout(nrow=2,byrow=F)
dev.off()
```

2(a)
```{r}
set.seed(123456)
group_image1=group_fun1(image1)
group_image2=group_fun1(image2)
group_image3=group_fun1(image3)
group_image1p=group_fun1(image1,drop_margin=TRUE)
group_image2p=group_fun1(image2,drop_margin=TRUE)
group_image3p=group_fun1(image3,drop_margin=TRUE)

group_images=rbind(group_image1,group_image2,group_image3)
group_imagesp=rbind(group_image1p,group_image2p,group_image3p)
```

```{r}
group_image1pp=group_fun2(image1)
group_image2pp=group_fun2(image2)
group_image3pp=group_fun2(image3)
group_imagespp=rbind(group_image1pp,group_image2pp,group_image3pp)
```

2(a)
```{r}
png(file="plot/split-persentage.png",units="in",width=3,
    height=2,pointsize=12,res=300)
group_imagespp%>%
  dplyr::select(c(3,12))%>%
  group_by(label,fold)%>%
  count()%>%
  pivot_wider(names_from=label,values_from=freq)%>%
  mutate(sum1=rowSums(.[,2:3]))%>%
  mutate(`not cloud`=percent(`-1`/sum1,accuracy=0.01),
         #unlabeled=percent(`0`/sum1,accuracy=0.01),
         cloud=percent(`1`/sum1,accuracy=0.01),
         Total="100%")%>%
  dplyr::select(c(1,5:7))%>%
  grid.table(rows=NULL)
dev.off()
  # knitr::kable(caption = "Percentage of Percentage of not cloud, unlabeled and cloud for each image.")%>%
  # save_kable("plot/percent-table.png")
```
2(a)
```{r}
png(file="plot/split-result1.png",units="in",width=7.5,
    height=3,pointsize=12,res=300)
rbind(group_image1%>%dplyr::select(c(1,2,12))%>%mutate(image="Image1"),
      group_image2%>%dplyr::select(c(1,2,12))%>%mutate(image="Image2"),
      group_image3%>%dplyr::select(c(1,2,12))%>%mutate(image="Image3"))%>%
  ggplot(aes(x,y,color=factor(fold)))+
  geom_point(shape=15,size=0.0000000000000001)+
  facet_wrap(~image)+
  coord_fixed()+
  guides(color = guide_legend(override.aes = list(size = 10)))+
  labs(x="x coordinate",y="y coordinate")+
  #scale_color_manual(values=c("#501d8a", "#e55709"),
   #                  labels=c("not cloud","cloud"))+
  theme(legend.position="right",legend.title=element_blank())
dev.off()
```
2(b)
```{r accuracy of trivial classifier}
test_data=group_images%>%filter(fold==6)
valid_data=group_images%>%filter(fold==5)
train_data=group_images%>%filter(fold!=6&fold!=5)

acc1_test=test_data%>%
  dplyr::select(c(3,12))%>%
  group_by(label,fold)%>%
  count()%>%
  pivot_wider(names_from=label,values_from=freq)%>%
  mutate(sum1=rowSums(.[,2:3]))%>%
  mutate(`not cloud`=percent(`-1`/sum1,accuracy=0.01),
         #unlabeled=percent(`0`/sum1,accuracy=0.01),
         cloud=percent(`1`/sum1,accuracy=0.01),
         Total="100%")%>%
  dplyr::select(c(5:7))%>%
  mutate(data="test",`split method`="block split")%>%
  dplyr::select(c(4,5,1:3))
acc1_valid=valid_data%>%
  dplyr::select(c(3,12))%>%
  group_by(label,fold)%>%
  count()%>%
  pivot_wider(names_from=label,values_from=freq)%>%
  mutate(sum1=rowSums(.[,2:3]))%>%
  mutate(`not cloud`=percent(`-1`/sum1,accuracy=0.01),
         #unlabeled=percent(`0`/sum1,accuracy=0.01),
         cloud=percent(`1`/sum1,accuracy=0.01),
         Total="100%")%>%
  dplyr::select(c(5:7))%>%
  mutate(data="valid",`split method`="block split")%>%
  dplyr::select(c(4,5,1:3))

test2_data=group_imagespp%>%filter(fold==6)
valid2_data=group_imagespp%>%filter(fold==5)
train2_data=group_imagespp%>%filter(fold!=6&fold!=5)

acc2_test=test2_data%>%
  dplyr::select(c(3,12))%>%
  group_by(label,fold)%>%
  count()%>%
  pivot_wider(names_from=label,values_from=freq)%>%
  mutate(sum1=rowSums(.[,2:3]))%>%
  mutate(`not cloud`=percent(`-1`/sum1,accuracy=0.01),
         #unlabeled=percent(`0`/sum1,accuracy=0.01),
         cloud=percent(`1`/sum1,accuracy=0.01),
         Total="100%")%>%
  dplyr::select(c(5:7))%>%
  mutate(data="test",`split method`="even split")%>%
  dplyr::select(c(4,5,1:3))
acc2_valid=valid2_data%>%
  dplyr::select(c(3,12))%>%
  group_by(label,fold)%>%
  count()%>%
  pivot_wider(names_from=label,values_from=freq)%>%
  mutate(sum1=rowSums(.[,2:3]))%>%
  mutate(`not cloud`=percent(`-1`/sum1,accuracy=0.01),
         #unlabeled=percent(`0`/sum1,accuracy=0.01),
         cloud=percent(`1`/sum1,accuracy=0.01),
         Total="100%")%>%
  dplyr::select(c(5:7))%>%
  mutate(data="valid",`split method`="even split")%>%
  dplyr::select(c(4,5,1:3))

png(file="plot/trivial-classifier.png",units = "in",width=4.2,
    height=1.5 ,pointsize=12,res=300)
rbind(acc1_test,acc1_valid,acc2_test,acc2_valid)%>%
  grid.table(rows=NULL)
dev.off()
```
2(c)
```{r,message=FALSE}
lr_model=glm(formula=factor(label)~1,
            group_images,family=binomial)
lr_for=step(lr_model,direction="forward",scope=~NDAI + SD + CORR + DF + CF + BF + AF + AN,steps=100)
```
```{r}
png(file="plot/best-features.png",units="in",width=5.3,
    height=3,pointsize=12,res=300)
lr_for$anova%>%
  grid.table(rows=NULL)
dev.off()

```
3(a)
```{r}
images=rbind(image1%>%mutate(image=1),image2%>%mutate(image=2),image3%>%mutate(image=3))
X=images%>%dplyr::select(-label)
y=images%>%dplyr::select(label)
K=6
```

```{r}
set.seed(123456)
LR_acc1=CVmaster(generic_fun="logistics",X,y,K,loss_fun=c("accuracy","prf","auc"),drop_margin0=FALSE)
LDA_acc1=CVmaster(generic_fun="LDA",X,y,K,loss_fun=c("accuracy","prf","auc"),drop_margin0=FALSE)
QDA_acc1=CVmaster(generic_fun="QDA",X,y,K,loss_fun=c("accuracy","prf","auc"),drop_margin0=FALSE)
NB_acc1=CVmaster(generic_fun="NB",X,y,K,loss_fun=c("accuracy","prf","auc"),drop_margin0=FALSE)
CART_acc1=CVmaster(generic_fun="CART",X,y,K,loss_fun=c("accuracy","prf","auc"),drop_margin0=FALSE)
```

```{r}
set.seed(123456)
LR_acc2=CVmaster(generic_fun="logistics",X,y,K,loss_fun=c("accuracy","prf","auc"),group_choice=2)
QDA_acc2=CVmaster(generic_fun="QDA",X,y,K,loss_fun=c("accuracy","prf","auc"),group_choice=2)
LDA_acc2=CVmaster(generic_fun="LDA",X,y,K,loss_fun=c("accuracy","prf","auc"),group_choice=2)
NB_acc2=CVmaster(generic_fun="NB",X,y,K,loss_fun=c("accuracy","prf","auc"),group_choice=2)
CART_acc2=CVmaster(generic_fun="CART",X,y,K,loss_fun=c("accuracy","prf","auc"),group_choice=2)
```

3(a)
```{r}
a=rbind(LR_acc1$acc,LR_acc2$acc,
        QDA_acc1$acc,QDA_acc2$acc,
        LDA_acc1$acc,LDA_acc2$acc,
        NB_acc1$acc,NB_acc2$acc,
        CART_acc1$acc,CART_acc2$acc)%>%
  data.frame()%>%
  mutate(`split method`=c("block split","even split"))%>%
  mutate(classifier=c("Logistic Regression","Logistic Regression",
                      "QDA","QDA",
                      "LDA","LDA",
                      "NB","NB",
                      "CART","CART"))%>%
  dplyr::select(c(9,8,1:7))
colnames(a)=c("classifier","split method",
              "Fold 1","Fold 2","Fold 3","Fold 4","Fold 5","Average","Test")
png(file="plot/cv-acc.png",units="in",width=9.6,
    height=3.2,pointsize=12,res=300)
a%>%
  grid.table(rows=NULL)
dev.off()
```
3(a)  lda qda assumption
```{r}
png(file="plot/density.png",units="in",width=5.3,
    height=3,pointsize=12,res=300)
p1=df1%>%
  filter(label==1)%>%
  ggplot(aes(NDAI,SD))+
  geom_density_2d()+labs(subtitle="cloud")
p2=df1%>%
  filter(label==1)%>%
  ggplot(aes(NDAI,CORR))+
  geom_density_2d()+labs(subtitle="cloud")
p3=df1%>%
  filter(label==1)%>%
  ggplot(aes(CORR,SD))+
  geom_density_2d()+labs(subtitle="cloud")
p4=df1%>%
  filter(label==-1)%>%
  ggplot(aes(NDAI,SD))+
  geom_density_2d()+labs(subtitle="not cloud")
p5=df1%>%
  filter(label==-1)%>%
  ggplot(aes(NDAI,CORR))+
  geom_density_2d()+labs(subtitle="not cloud")
p6=df1%>%
  filter(label==-1)%>%
  ggplot(aes(CORR,SD))+
  geom_density_2d()+labs(subtitle="not cloud")

pp7=p1+p2+p3+p4+p5+p6+plot_layout(nrow=2,byrow=T)
png(file="plot/density.png",units="in",width=5.3,
    height=3,pointsize=12,res=300)
pp7
dev.off()
```

3(b)
```{r}
perf.all=data.frame()
split1.list=list(LR_acc1,QDA_acc1,LDA_acc1,NB_acc1,CART_acc1)
split1.name=c("LR","QDA","LDA","NB","CART")
for (i in seq_along(split1.list)){
  res=split1.list[[i]]
  pred=prediction(res$prob,res$gold)
  perf=performance(pred,"tpr","fpr")
  model.perf<-data.frame(slot(perf,"x.values")[[1]],
                        slot(perf,"y.values")[[1]],
                        slot(perf,"alpha.values")[[1]],
                        split1.name[i])
  colnames(model.perf)=c(slot(perf,"x.name"),slot(perf,"y.name"),
                         slot(perf,"alpha.name"),"model")
  perf.all=rbind(perf.all,model.perf)
}
cutoff=perf.all%>%
  mutate(youden=`True positive rate`-`False positive rate`)%>%
  group_by(model)%>%
  filter(youden==max(youden))%>%
  select(model,Cutoff)%>%
  ungroup()
png(file="plot/roc.png",units="in",width=5,
    height=4 ,pointsize=12,res=300)
perf.all%>%
  ggplot(aes(x=`False positive rate`,y=`True positive rate`))+
  geom_line(aes(group=model,color=model))+
  geom_point(data=merge(perf.all,cutoff,by=c("model","Cutoff")),aes(color=model),shape=4,size=3)+
  geom_text_repel(data=merge(perf.all,cutoff,by=c("model","Cutoff")),aes(label=round(Cutoff,4),color=model))
dev.off()
```
3(c)
```{r}
b=rbind(c(LR_acc1$prf,LR_acc1$auc),
        c(LR_acc2$prf,LR_acc2$auc),
        c(QDA_acc1$prf,QDA_acc1$auc),
        c(QDA_acc2$prf,QDA_acc2$auc),
        c(LDA_acc1$prf,LDA_acc1$auc),
        c(LDA_acc2$prf,LDA_acc2$auc),
        c(NB_acc1$prf,NB_acc1$auc),
        c(NB_acc2$prf,NB_acc2$auc),
        c(CART_acc1$prf,CART_acc1$auc),
        c(CART_acc2$prf,CART_acc2$auc))%>%
  data.frame()%>%
  mutate(`split method`=c("block split","even split"))%>%
  mutate(classifier=c("Logistic Regression","Logistic Regression",
                      "QDA","QDA",
                      "LDA","LDA",
                      "NB","NB",
                      "CART","CART"))%>%
  dplyr::select(classifier,`split method`,1:4)
colnames(b)=c("classifier","split method",
              "precision","recall","f1","auc")
png(file="plot/test-prf.png",units="in",width=7,
    height=3.2,pointsize=12,res=300)
b%>%
  grid.table(rows=NULL)
dev.off()
```
4(a)
```{r}
model=LR_acc1$model
summary(model)
```
```{r}
png(file="plot/lr_coef.png",units="in",width=5.5,
    height=2,pointsize=12,res=300)
coef(summary(model))[,c(1,3,4)]%>%
  grid.table()
dev.off()
```
```{r}
png(file="plot/lr_smr.png",units="in",width=6,
    height=1,pointsize=12,res=300)
data.frame(`No.Iteration`=model$iter,
           Convergence=model$converged,
           `Null deviance`=model$null.deviance,
           `Residual deviance`=model$deviance)%>%
  grid.table(row=NULL)
dev.off()
```
```{r}
train_data=LR_acc1$train
train_x=train_data%>%select(NDAI,CORR,SD)
pca_prcomp <- prcomp(train_x,scale.=TRUE)
summary(pca_prcomp)
```
```{r}
png(file="plot/lr_pca.png",units="in",width=7,
    height=3,pointsize=12,res=300)
trn_pca=train_x%>%PCA(graph = FALSE)

proj=trn_pca$ind$coord[,1:2]%>%
  data.frame()%>%
  tibble()%>%
  mutate(label = train_data$label,
         pred = sign(LR_acc1$score-0.5))%>%
  mutate(eval=case_when(pred==label&label==1~"TP",
                        pred==label&label==-1~"TN",
                        pred!=label&pred==1~"FP",
                        TRUE~"FN"))

p1=proj%>% 
  ggplot(aes(x = Dim.1, y = Dim.2))+
  geom_point(aes(color=eval),size=0.00001)+
  labs(x="PC1",y="PC2",title="PCA Projections")+
  guides(color=guide_legend(override.aes=list(size=2)))+
  theme_bw()

p2=plot(trn_pca,choix="var")
p1+p2

dev.off()
```

```{r}
png(file="plot/lr_linearity.png",units="in",width=7,
    height=3,pointsize=12,res=300)
train_x$prob=LR_acc1$score
predictors=colnames(train_x)
train_x%>%
  mutate(logit=log(prob/(1-prob)))%>%
  select(-prob)%>%
  sample_n(10000)%>%
  gather(key="predictors",value="predictor.value",-logit)%>%
  ggplot(aes(logit,predictor.value))+
  geom_point(size=0.01,alpha=0.5)+
  geom_smooth(method="loess")+
  theme_bw() + 
  facet_wrap(~predictors,scales="free_y")
dev.off()
```
```{r}
png(file="plot/lr_collinearity.png",units="in",width=5,
    height=0.5,pointsize=12,res=300)
data.frame(t(vif(model)))%>%
  grid.table(row=NULL)
dev.off()
```
4(b)
```{r} 
png(file="plot/misclf_spatial.png",units="in",width=7,
    height=3,pointsize=12,res=300)
test_data=NB_acc1$test
test_data$pred=sign(NB_acc1$prob-as.numeric(cutoff%>%filter(model=="NB")%>%select(Cutoff)))
test_data_eval=test_data%>%mutate(eval=case_when(pred==label&label==1~"TP",
                                                 pred==label&label==-1~"TN",
                                                 pred!=label&pred==1~"FP",
                                                 TRUE~"FN"))
test_data_eval%>% 
  dplyr::select(-c(pred,fold))%>%
  rbind(images%>%filter(label==0)%>%mutate(eval="Unlabeled"))%>%
  ggplot(aes(x,y,color =eval))+
  geom_point(shape=15,size=0.00000000000001)+
  facet_wrap(~image)+
  coord_fixed()+
  guides(color = guide_legend(override.aes = list(size = 10)))+
  labs(x="x coordinate",y="y coordinate")+
  theme(legend.position="right",legend.title=element_blank())
dev.off()
```

```{r}
table(test_data$pred,test_data$label)
```

```{r}
png(file="plot/misclf_feature.png",units="in",width=8,
    height=3,pointsize=12,res=300)

p1=test_data_eval%>%
  ggplot(aes(x=NDAI,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p2=test_data_eval%>%
  ggplot(aes(x=NDAI,y=CORR))+
  geom_point(aes(color=eval),size=0.1)

p3=test_data_eval%>%
  ggplot(aes(x=CORR,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p1+p2+p3+plot_layout(nrow=1)
dev.off()
```

```{r}
png(file="plot/misclf_density.png",units="in",width=8,
    height=3,pointsize=12,res=300)
test_data_eval%>% 
  dplyr::select(NDAI:CORR,eval)%>%
  pivot_longer(NDAI:CORR,names_to="feature",values_to="value")%>%
  ggplot(aes(x=value))+
  geom_density(aes(fill=eval,color=eval),alpha=0.3)+
  facet_wrap(~feature,scales="free")+
  # coord_fixed()+
  guides(color=guide_legend(override.aes=list(size=10)))+
  labs(x="feature value")+
  theme(legend.position="right",legend.title=element_blank())
dev.off()
```

```{r}
png(file="plot/misclf_spatial_qda.png",units="in",width=7,
    height=3,pointsize=12,res=300)
test_data_qda=QDA_acc1$test
test_data_qda$pred=sign(QDA_acc1$prob-as.numeric(cutoff%>%filter(model=="QDA")%>%select(Cutoff)))
test_data_eval_qda=test_data_qda%>%mutate(eval=case_when(pred==label&label==1~"TP",
                                                 pred==label&label==-1~"TN",
                                                 pred!=label&pred==1~"FP",
                                                 TRUE~"FN"))
test_data_eval_qda%>% 
  dplyr::select(-c(pred,fold))%>%
  rbind(images%>%filter(label==0)%>%mutate(eval="Unlabeled"))%>%
  ggplot(aes(x,y,color =eval))+
  geom_point(shape=15,size=0.00000000000001)+
  facet_wrap(~image)+
  coord_fixed()+
  guides(color = guide_legend(override.aes = list(size = 10)))+
  labs(x="x coordinate",y="y coordinate")+
  # scale_color_manual(values=c("#501d8a", "#1c8041", "#e55709"),
  #                    labels=c("not cloud","unlabeled","cloud"))+
  theme(legend.position="right",legend.title=element_blank())
dev.off()
```

```{r}
png(file="plot/misclf_feature_qda.png",units="in",width=8,
    height=3,pointsize=12,res=300)

p1=test_data_eval_qda%>%
  ggplot(aes(x=NDAI,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p2=test_data_eval_qda%>%
  ggplot(aes(x=NDAI,y=CORR))+
  geom_point(aes(color=eval),size=0.1)

p3=test_data_eval_qda%>%
  ggplot(aes(x=CORR,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p1+p2+p3+plot_layout(nrow=1)
dev.off()
```

```{r}
png(file="plot/misclf_feature_lda.png",units="in",width=8,
    height=3,pointsize=12,res=300)
test_data_lda=LDA_acc1$test
test_data_lda$pred=sign(LDA_acc1$prob-as.numeric(cutoff%>%filter(model=="LDA")%>%select(Cutoff)))
test_data_eval_lda=test_data_lda%>%mutate(eval=case_when(pred==label&label==1~"TP",
                                                 pred==label&label==-1~"TN",
                                                 pred!=label&pred==1~"FP",
                                                 TRUE~"FN"))
p1=test_data_eval_lda%>%
  ggplot(aes(x=NDAI,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p2=test_data_eval_lda%>%
  ggplot(aes(x=NDAI,y=CORR))+
  geom_point(aes(color=eval),size=0.1)

p3=test_data_eval_lda%>%
  ggplot(aes(x=CORR,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p1+p2+p3+plot_layout(nrow=1)
dev.off()
```
```{r}
png(file="plot/misclf_feature_cart.png",units="in",width=8,
    height=3,pointsize=12,res=300)
test_data_cart=CART_acc1$test
test_data_cart$pred=sign(CART_acc1$prob-as.numeric(cutoff%>%filter(model=="CART")%>%select(Cutoff)))
test_data_eval_cart=test_data_lda%>%mutate(eval=case_when(pred==label&label==1~"TP",
                                                 pred==label&label==-1~"TN",
                                                 pred!=label&pred==1~"FP",
                                                 TRUE~"FN"))
p1=test_data_eval_cart%>%
  ggplot(aes(x=NDAI,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p2=test_data_eval_cart%>%
  ggplot(aes(x=NDAI,y=CORR))+
  geom_point(aes(color=eval),size=0.1)

p3=test_data_eval_cart%>%
  ggplot(aes(x=CORR,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p1+p2+p3+plot_layout(nrow=1)
dev.off()
```
```{r}
png(file="plot/misclf_feature_lr.png",units="in",width=8,
    height=3,pointsize=12,res=300)
test_data_lr=LR_acc1$test
test_data_lr$pred=sign(LR_acc1$prob-as.numeric(cutoff%>%filter(model=="LR")%>%select(Cutoff)))
test_data_eval_lr=test_data_lda%>%mutate(eval=case_when(pred==label&label==1~"TP",
                                                 pred==label&label==-1~"TN",
                                                 pred!=label&pred==1~"FP",
                                                 TRUE~"FN"))
p1=test_data_eval_lr%>%
  ggplot(aes(x=NDAI,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p2=test_data_eval_lr%>%
  ggplot(aes(x=NDAI,y=CORR))+
  geom_point(aes(color=eval),size=0.1)

p3=test_data_eval_lr%>%
  ggplot(aes(x=CORR,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p1+p2+p3+plot_layout(nrow=1)
dev.off()
```
4(c)
```{r}
set.seed(123456)
RF_acc1=CVmaster(generic_fun="RF",X,y,K,loss_fun=c("accuracy"),drop_margin0=FALSE)
RF_acc2=CVmaster(generic_fun="RF",X,y,K,loss_fun=c("accuracy"),group_choice=2)
ESB_acc1=CVmaster(generic_fun="KNN+QDA+NB",X,y,K,loss_fun=c("accuracy"),drop_margin0=FALSE)
ESB_acc2=CVmaster(generic_fun="KNN+QDA+NB",X,y,K,loss_fun=c("accuracy"),group_choice=2)
```

```{r}
LOGLR_acc1=CVmaster(generic_fun="LOGLR",X,y,K,loss_fun=c("accuracy"),drop_margin0=FALSE)
LOGLR_acc2=CVmaster(generic_fun="LOGLR",X,y,K,loss_fun=c("accuracy"),group_choice=2)
```

```{r}
KNN_acc1=CVmaster(generic_fun="KNN",X,y,K,loss_fun=c("accuracy"),drop_margin0=FALSE)
KNN_acc2=CVmaster(generic_fun="KNN",X,y,K,loss_fun=c("accuracy"),group_choice=2)
```

```{r}
e=rbind(RF_acc1$acc,RF_acc2$acc,
        ESB_acc1$acc,ESB_acc2$acc,
        LOGLR_acc1$acc,LOGLR_acc2$acc,
        KNN_acc1$acc,KNN_acc2$acc)%>%
  data.frame()%>%
  mutate(`split method`=c("block split","even split"))%>%
  mutate(classifier=c("Random Forest","Random Forest",
                      "Ensemble Model","Ensemble Model",
                      "LOGLR","LOGLR",
                      "KNN","KNN"))%>%
  dplyr::select(classifier,`split method`,1)
colnames(e)=c("classifier","split method",
              "test accuracy")
png(file="plot/better-model-accuracy.png",units="in",width=4,
    height=2.5,pointsize=12,res=300)
e%>%
  grid.table(rows=NULL)
dev.off()
```
4(d)
```{r}
model=LR_acc2$model
summary(model)
```
```{r}
train_data=LR_acc2$train
train_x=train_data%>%select(NDAI,CORR,SD)
trn_pca=train_x%>%PCA(graph = FALSE)

proj=trn_pca$ind$coord[,1:2]%>%
  data.frame()%>%
  tibble()%>%
  mutate(label = train_data$label,
         pred = sign(LR_acc2$score-0.5))%>%
  mutate(eval=case_when(pred==label&label==1~"TP",
                        pred==label&label==-1~"TN",
                        pred!=label&pred==1~"FP",
                        TRUE~"FN"))

p1=proj%>% 
  ggplot(aes(x = Dim.1, y = Dim.2))+
  geom_point(aes(color=eval),size=0.00001)+
  labs(x="PC1",y="PC2",title="PCA Projections")+
  guides(color=guide_legend(override.aes=list(size=2)))+
  theme_bw()

p2=plot(trn_pca,choix="var")
p1+p2
```
```{r}
train_x$prob=LR_acc2$score
predictors=colnames(train_x)
train_x%>%
  mutate(logit=log(prob/(1-prob)))%>%
  select(-prob)%>%
  sample_n(10000)%>%
  gather(key="predictors",value="predictor.value",-logit)%>%
  ggplot(aes(logit,predictor.value))+
  geom_point(size=0.01,alpha=0.5)+
  geom_smooth(method="loess")+
  theme_bw() + 
  facet_wrap(~predictors,scales="free_y")
```
```{r}
vif(model)
```
```{r}
test_data=NB_acc2$test
test_data$pred=sign(NB_acc2$prob-as.numeric(cutoff%>%filter(model=="NB")%>%select(Cutoff)))
test_data_eval=test_data%>%mutate(eval=case_when(pred==label&label==1~"TP",
                                                 pred==label&label==-1~"TN",
                                                 pred!=label&pred==1~"FP",
                                                 TRUE~"FN"))
test_data_eval%>% 
  dplyr::select(-c(pred,fold))%>%
  rbind(images%>%filter(label==0)%>%mutate(eval="Unlabeled"))%>%
  ggplot(aes(x,y,color =eval))+
  geom_point(shape=15,size=0.00000000000001)+
  facet_wrap(~image)+
  coord_fixed()+
  guides(color=guide_legend(override.aes=list(size=10)))+
  labs(x="x coordinate",y="y coordinate")+
  # scale_color_manual(values=c("#501d8a", "#1c8041", "#e55709"),
  #                    labels=c("not cloud","unlabeled","cloud"))+
  theme(legend.position="right",legend.title=element_blank())
```
```{r}
p1=test_data_eval%>%
  ggplot(aes(x=NDAI,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p2=test_data_eval%>%
  ggplot(aes(x=NDAI,y=CORR))+
  geom_point(aes(color=eval),size=0.1)

p3=test_data_eval%>%
  ggplot(aes(x=CORR,y=SD))+
  geom_point(aes(color=eval),size=0.1)

p1+p2+p3+plot_layout(nrow=1)
```











